export default function handler(req, res) {

  const list = {
    series: [
      {
        title: 'Detectiv Conan',
        link_url: 'detectiv-conan',
        type: 'series',
        thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg',
        description: 'Messerscharfer Verstand, geniale Kombinationsgabe – mit gerade mal 17 Jahren gilt Shin’ichi Kudô bereits als Meisterdetektiv. Immer wieder hilft er der Polizei dabei, die kniffligsten Fälle zu lösen. Eines Tages jedoch beobachtet er zwei Männer in Schwarz bei einem verdächtigen Deal. Dabei bemerkt er den Verbrecher hinter sich nicht, der ihm ein mysteriöses Gift verabreicht. Schließlich erwacht Shin’ichi im Körper eines Grundschülers. Um nicht wieder ins Visier der Schwarzen Organisation zu geraten, lebt er fortan bei seiner Freundin Ran. Aufgepasst, hier kommt der kleine Detektiv Conan!',
        episodeNumbers: '',       
        series: [
          { id: 3, title: "Die Doppelgängering", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film A", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/003%20Detektiv%20Conan%20Die%20Doppelg%C3%A4ngerin.mp4" },
          { id: 4, title: "Auf Schatzsuche", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/004%20Detektiv%20Conan%20Auf%20Schatzsuche.mp4" },
          { id: 11, title: "Mord bei Mondschein", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/011%20Detektiv%20Conan%20Mord%20bei%20Mondschein.mp4" },
          { id: 12, title: "Der Schein trügt", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/12%20Detektiv%20Conan%20Der%20Schein%20tr%C3%BCgt.mp4" },
          { id: 15, title: "Der Tote im Badezimmer", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/15%20Detektiv%20Conan%20Der%20Tote%20im%20Badezimmer.mp4" },
          { id: 17, title: "Eine Nacht im Kaufhaus", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/17%20Detektiv%20Conan%20Eine%20Nacht%20im%20Kaufhaus.mp4" },
          { id: 20, title: "Eine gespenstische Entdeckung", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/20%20Detektiv%20Conan%20Eine%20gespenstische%20Entdeckung.mp4" },
          { id: 22, title: "Das Albtraumschiff (1)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/22%20Detektiv%20Conan%20Das%20Albtraumschiff%20(1).mp4" },
          { id: 23, title: "Das Albtraumschiff (2)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/23%20Detektiv%20Conan%20Das%20Albtraumschiff%20(2).mp4" },
          { id: 33, title: "Der Schatz der Erfahrung", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/33%20Detektiv%20Conan%20Der%20Schatz%20der%20Erfahrung.mp4" },
          { id: 34, title: "Die Mumie im Wald (1)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/34%20Detektiv%20Conan%20Die%20Mumie%20im%20Wald%20(1).mp4" },
          { id: 35, title: "Die Mumie im Wald (2)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/35%20Detektiv%20Conan%20Die%20Mumie%20im%20Wald%20(2).mp4" },
          { id: 38, title: "Feuer und Flamme", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/38%20Detektiv%20Conan%20Feuer%20und%20Flamme.mp4" },
          { id: 39, title: "Geld stinkt nicht (1)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/39%20Detektiv%20Conan%20Geld%20stinkt%20nicht%20(1).mp4" },
          { id: 40, title: "Geld stinkt nicht (2)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/40%20Detektiv%20Conan%20Geld%20stinkt%20nicht%20(2).mp4" },
          { id: 46, title: "Mediziner unter sich", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/46%20Detektiv%20Conan%20Mediziner%20unter%20sich.mp4" },
          { id: 50, title: "Der verschwundene Bibliothekar", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/50%20Detektiv%20Conan%20Der%20verschwundene%20Bibliothekar.mp4" },
          { id: 51, title: "Sport ist Mord", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/51%20Detektiv%20Conan%20Sport%20ist%20Mord.mp4" },
          { id: 57, title: "Rache für Sherlock Holmes (1)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/57%20Detektiv%20Conan%20Rache%20f%C3%BCr%20Sherlock%20Holmes%20(1).mp4" },
          { id: 58, title: "Rache für Sherlock Holmes (2)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/58%20Detektiv%20Conan%20Rache%20f%C3%BCr%20Sherlock%20Holmes%20(2).mp4" },
          { id: 61, title: "Der Fluch der Suigun (1)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/61%20Detektiv%20Conan%20Der%20Fluch%20der%20Suigun%20(1).mp4" },
          { id: 62, title: "Der Fluch der Suigun (2)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/62%20Detektiv%20Conan%20Der%20Fluch%20der%20Suigun%20(2).mp4" },
          { id: 73, title: "SOS per Flaschenpost", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/73%20Detektiv%20Conan%20SOS%20per%20Flaschenpost.mp4" },
          { id: 74, title: "Jinnai, der Todesengel", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/74%20Detektiv%20Conan%20Jinnai%2C%20der%20Todesengel.mp4" },
          { id: 77, title: "Späte Sühne (1)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/077%20Detektiv%20Conan%20Sp%C3%A4te%20S%C3%BChne%20(1).mp4" },
          { id: 78, title: "Späte Sühne (2)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/078%20Detektiv%20Conan%20Sp%C3%A4te%20S%C3%BChne%20(2).mp4" },
          { id: 81, title: "Gefährliche Töne (1)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/081%20Detektiv%20Conan%20Gef%C3%A4hrliche%20T%C3%B6ne%20(1).mp4" },
          { id: 82, title: "Gefährliche Töne (2)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/082%20Detektiv%20Conan%20Gef%C3%A4hrliche%20T%C3%B6ne%20(2).mp4" },
          { id: 92, title: "Auf der Suche nach Fox (1)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/092%20Detektiv%20Conan%20Auf%20der%20Suche%20nach%20Fox%20(1).mp4" },
          { id: 93, title: "Auf der Suche nach Fox (2)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/093%20Detektiv%20Conan%20Auf%20der%20Suche%20nach%20Fox%20(2).mp4" },
          { id: 106, title: "Mord mit Blitzlicht", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/106%20Detektiv%20Conan%20Mord%20mit%20Blitzlicht.mp4" },
          { id: 112, title: "Nächtlicher Spuk in der Schule", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/112%20Detektiv%20Conan%20N%C3%A4chtlicher%20Spuk%20in%20der%20Schule.mp4" },
          { id: 123, title: "Zahlenspiele", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/123%20Detektiv%20Conan%20Zahlenspiele.mp4" },
          { id: 136, title: "Das Geheimnis des alten Schlosses (1)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/136%20Detektiv%20Conan%20Das%20Geheimnis%20des%20alten%20Schlosses%20(1).mp4" },
          { id: 137, title: "Das Geheimnis des alten Schlosses (2)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/137%20Detektiv%20Conan%20Das%20Geheimnis%20des%20alten%20Schlosses%20(2).mp4" },
          { id: 144, title: "Mord im Speisewagen (1)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/144%20Detektiv%20Conan%20Mord%20im%20Speisewagen%20(1).mp4" },
          { id: 145, title: "Mord im Speisewagen (2)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/145%20Detektiv%20Conan%20Mord%20im%20Speisewagen%20(2).mp4" },
          { id: 159, title: "Der Fluch der Pagode (1)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/159%20Detektiv%20Conan%20Der%20Fluch%20der%20Pagode%20(1).mp4" },
          { id: 160, title: "Der Fluch der Pagode (2)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/160%20Detektiv%20Conan%20Der%20Fluch%20der%20Pagode%20(2).mp4" },
          { id: 163, title: "Sonne, Mond und Sterne (1)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/163%20Detektiv%20Conan%20Sonne%2C%20Mond%20und%20Sterne%20(1).mp4" },
          { id: 164, title: "Sonne, Mond und Sterne (2)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/164%20Detektiv%20Conan%20Sonne%2C%20Mond%20und%20Sterne%20(2).mp4" },
          { id: 165, title: "Die verschwundenen Kinder", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/165%20Detektiv%20Conan%20Die%20verschwundenen%20Kinder.mp4" },
          { id: 166, title: "Die Spinnenkönigin (1)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/166%20Detektiv%20Conan%20Die%20Spinnenk%C3%B6nigin%20(1).mp4" },
          { id: 167, title: "Die Spinnenkönigin (2)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/167%20Detektiv%20Conan%20Die%20Spinnenk%C3%B6nigin%20(2).mp4" },
          { id: 168, title: "Die Spinnenkönigin (3)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/168%20Detektiv%20Conan%20Die%20Spinnenk%C3%B6nigin%20(3).mp4" },
          { id: 179, title: "Unfall Niemals!", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/179%20Detektiv%20Conan%20Unfall_%20Niemals!.mp4" },
          { id: 183, title: "Der geheimnisvolle Kunde", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/183%20Detektiv%20Conan%20Der%20geheimnisvolle%20Kunde.mp4" },
          { id: 184, title: "Das Haus der 200 Masken (1 + 2)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/184%20Detektiv%20Conan%20Das%20Haus%20der%20200%20Masken%20(1%202).mp4" },
          { id: 208, title: "Der Zorn der Berggöttin (1 + 2)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/208%20Detektiv%20Conan%20Der%20Zorn%20der%20Bergg%C3%B6ttin%20(1%202).mp4" },
          { id: 212, title: "Der Wald, die Bären, die Jäger (1)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/212%20Detektiv%20Conan%20Der%20Wald%2C%20die%20B%C3%A4ren%2C%20die%20J%C3%A4ger%20(1).mp4" },
          { id: 213, title: "Der Wald, die Bären, die Jäger (2)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/213%20Detektiv%20Conan%20Der%20Wald%2C%20die%20B%C3%A4ren%2C%20die%20J%C3%A4ger%20(2).mp4" },
          { id: 222, title: "Der Pfeil der Sirene (1)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/222%20Detektiv%20Conan%20Der%20Pfeil%20der%20Sirene%20(1).mp4" },
          { id: 223, title: "Der Pfeil der Sirene (2)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/223%20Detektiv%20Conan%20Der%20Pfeil%20der%20Sirene%20(2).mp4" },
          { id: 224, title: "Der Pfeil der Sirene (3)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/224%20Detektiv%20Conan%20Der%20Pfeil%20der%20Sirene%20(3).mp4" },
          { id: 415, title: "Der böse Geist, der an Butsumetsu-Tagen umgeht (1)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "" },
          { id: 416, title: "Der böse Geist, der an Butsumetsu-Tagen umgeht (2)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "" },
          { id: 417, title: "Der böse Geist, der an Butsumetsu-Tagen umgeht (3)", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Episodes.jpeg', description: "Beschreibung von Film B", url: "" },
        ]
      }
    ],

    movies: [
      {
        title: 'Detectiv Conan Movies',
        link_url: 'detectiv-conan',
        type: 'movies',
        thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Movies.jpeg',
        description: 'Die Filmreihe von Detektiv Conan.',
        movieNumber: '',
        movies: [
          { id: 3, title: "Der Magier des letzten Jahrhunderts", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Movies.jpeg', description: "Kaito kündigt an, ein wertvolles Fabergé-Ei zu stehlen. Um dies zu verhindern, bittet der Veranstalter um Hilfe. Doch trotz der strengen Sicherheitsmaßnahmen gelingt es dem Dieb, das wertvolle Kleinod zu entwenden.", url: "https://shdw-drive.genesysgo.net/FehreygeoDp3VMmYNWrkUMQHek9x2rsFxdvzbcPv7iD1/Der%20Magier%20des%20letzten%20Jahrhunderts%20-%20Detektiv%20Conan.mp4" },
          { id: 4, title: "Der Killer in ihren Augen", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Movies.jpeg', description: "Ran schwebt in Lebensgefahr! Während sich Takagi und Chiba als ihre Bodyguards abwechseln, versucht Conan so schnell wie möglich den Täter zu enttarnen und Rans Erinnerungen zurückzuholen ...", url: "https://shdw-drive.genesysgo.net/FehreygeoDp3VMmYNWrkUMQHek9x2rsFxdvzbcPv7iD1/Der%20Killer%20in%20ihren%20Augen%20-%20Detektiv%20Conan.mp4" },
          { id: 5, title: "Coutdown zum Himmel", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Movies.jpeg', description: "Als eine Mordserie beginnt muss Conan nicht nur die Verbrechen aufklären, sondern auch wissen, was die mysteriöse Organisation damit zu tun hat. Außerdem verhält sich Haibara ausgesprochen merkwürdig.", url: "https://shdw-drive.genesysgo.net/FehreygeoDp3VMmYNWrkUMQHek9x2rsFxdvzbcPv7iD1/Coutdown%20zum%20Himmel%20-%20Detektiv%20Conan.mp4" },
          { id: 7, title: "Die Kreuzung des Labyrinths", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Movies.jpeg', description: "", url: "https://shdw-drive.genesysgo.net/FehreygeoDp3VMmYNWrkUMQHek9x2rsFxdvzbcPv7iD1/Die%20Kreuzung%20des%20Labyrinths%20-%20Detektiv%20Conan.mp4" },
          { id: 12, title: "Die Parnitur des Grauens", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Movies.jpeg', description: "In der Musikerszene gibt es eine Reihe von Sprengstoffanschlägen mit Todesopfern. Schlüssel zur Aufklärung der Fälle ist ein falscher Ton, den nur Menschen mit einem 'absoluten Gehör' erkennen.", url: "https://shdw-drive.genesysgo.net/FehreygeoDp3VMmYNWrkUMQHek9x2rsFxdvzbcPv7iD1/Die%20Parnitur%20des%20Grauens%20-%20Detektiv%20Conan.mp4" },
          { id: 16, title: "Der 11. Stürmer", thumbnail: 'https://shdw-drive.genesysgo.net/BiVmb2T6GY3vWNWYg8ojh1Tjyeiejkot8ZNB7WwRJWAL/Movies.jpeg', description: "Ein anonymer Attentäter droht damit, eine Bombe in einem voll besetzten Fußballstadium zu zünden. Conan bleibt nicht viel Zeit, eine Mega-Katastrophe zu verhindern.", url: "https://shdw-drive.genesysgo.net/FehreygeoDp3VMmYNWrkUMQHek9x2rsFxdvzbcPv7iD1/Der%2011.%20St%C3%BCrmer%20-%20Detektiv.Conan.mp4" },
        ]
      }
    ]
  }

    ;

  res.status(200).json(list);
}






