import { useRequireAuth } from '@/hooks/useRequireAuth';
import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';
import { fetchEpisodes } from '@/utils/apiHelpers';
import Link from 'next/link';
import Image from 'next/image';
import Head from 'next/head';
import styles from '@/styles/Home.module.css'
import Header from '@/components/header';

import Episode from '@/public/Episodes.jpeg'

export default function TypeList() {

  useRequireAuth();

  const [episodes, setEpisodes] = useState([]);
  const [loading, setLoading] = useState(true);
  const router = useRouter();
  const { type } = router.query;

  useEffect(() => {
    fetchEpisodes()
      .then(data => {
        setEpisodes(data);
        setLoading(false);
      })
      .catch(error => {
        console.error('Fehler beim Abrufen der Episoden.');
        setLoading(false);
      });
  }, []);

  if (loading) return <div style={{
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100vh'
  }}>Lade Episoden...</div>;

  const test = episodes[type] ? episodes[type][0] : [];

  function truncateTitle(title, maxLength = 30) {
    if (title.length <= maxLength) return title;
    return title.slice(0, maxLength) + '...';
  }

  return (
    <>
      <Head>
        <title>{test.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Header />
      <div className={styles.episodeGrid} style={{ marginTop: 100 }}>
        <li
          className={styles.episodeCard}
        >
          <Link href={`/${type}/${test.link_url}/list`}>
            <Image
              src={test.thumbnail || Episode}
              alt='Episode'
              width={300}
              height={400}
              className={styles.episodeImage}
              priority
            />
            <p title={test.title}>{truncateTitle(test.title)}</p>
          </Link>
        </li>
      </div>
    </>
  );
}