import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';
import { useRequireAuth } from '@/hooks/useRequireAuth';
import fetchDataFromFirestore from '@/utils/firebaseHelper';
import Head from 'next/head';
import styles from '@/styles/Home.module.css'
import Header from '@/components/header';
import Card from '@/components/Card';
import Loading from '@/components/Loading';

export default function TypeList() {

  useRequireAuth();

  const [episodes, setEpisodes] = useState([]);
  const [loading, setLoading] = useState(true);
  const router = useRouter();
  const { type } = router.query;

  useEffect(() => {

    if (!type) return;

    const getData = async () => {
      const video = await fetchDataFromFirestore(type, "detectiv-conan");

      if (video) {
        setEpisodes(video)
        setLoading(false);
      }
    };

    getData();

  }, [type]);

  if (loading) return <>
    <Loading />
  </>;

  return (
    <>
      <Head>
        <title>{episodes.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Header />
      <div className={styles.episodeGrid} style={{ marginTop: 100 }}>
        <li className={styles.episodeCard}>
          <Card title={episodes.title} url={`/browse/${type}/${episodes.link_url}/list`} thumbnail={episodes.thumbnail} />
        </li>
      </div>
    </>
  );
}