import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react';
import Link from 'next/link';
import Header from '@/components/header';

import Episode from '@/public/assets/images/Episodes.jpeg'
import DetektivConan from '@/public/assets/images/DetektivConan.jpeg'

export default function Home() {
  const [episodes, setEpisodes] = useState([]);
  const [links, setLink] = useState([]);
  const [movies, setMovie] = useState([]); 
  const [infos, setInfos] = useState([]); 

  useEffect(() => {
    fetch('/api/list')  // Annahme, dass dies der Endpunkt ist, um alle Episoden zu erhalten
      .then(response => response.json())
      .then(data => {
        setEpisodes(data.series[0].series);
        setLink(data.series[0]);
        setMovie(data.movies[0].movies);
        setInfos(data.movies[0]);
      })
      .catch(error => console.error('Fehler beim Abrufen der Episoden:', error));
  }, []);

  function shuffleArray(array) {
    let currentIndex = array.length, randomIndex;

    // Während es noch Elemente zum Mischen gibt...
    while (currentIndex !== 0) {

      // Wähle ein verbleibendes Element...
      randomIndex = Math.floor(Math.random() * currentIndex);
      currentIndex--;

      // Und tausche es mit dem aktuellen Element.
      [array[currentIndex], array[randomIndex]] = [array[randomIndex], array[currentIndex]];
    }

    return array;
  }

  const randomEpisode = shuffleArray([...episodes]).slice(0, 6);
  const randomMovie = shuffleArray([...movies]).slice(0, 6);

  return (
    <>
      <Head>
        <title>Netflix | Startseite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <main>

        <div
          style={{
            backgroundImage: `url(${DetektivConan.src})`,
            backgroundColor: '#141414',
            backgroundPosition: 'center',
            backgroundRepeat: 'no-repeat',
            width: '100%',
            height: '80vh',
          }}
        >
        </div>

        <div className={styles.info}>
          <h4>
            {links.title}
          </h4>
          <Link href={`/${links.type}/${links.link_url}/list`}>
            Mehr Anzeigen
          </Link>
        </div>

        <div className={styles.episodeGrid}>
          {randomEpisode.map((episode) => (
            <li
              key={episode.id}
              className={styles.episodeCard}
            >
              <Link href={`/${links.type}/${links.link_url}/episode/${episode.id}`}>
                <Image
                  src={episode.thumbnail || Episode}
                  alt='Episode'
                  width={300}
                  height={400}
                  priority
                />
                <p>{episode.title}</p>
              </Link>
            </li>
          ))}
        </div>

        <div className={styles.info}>
          <h4>
            {infos.title}
          </h4>
          <Link href={`/${infos.type}/${infos.link_url}/list`}>
            Mehr Anzeigen
          </Link>
        </div>

        <div className={styles.episodeGrid}>
          {randomMovie.map((episode) => (
            <li
              key={episode.id}
              className={styles.episodeCard}
            >
              <Link href={`/${infos.type}/${infos.link_url}/episode/${episode.id}`}>
                <Image
                  src={episode.thumbnail || Episode}
                  alt='Episode'
                  width={300}
                  height={400}
                  priority
                />
                <p>{episode.title}</p>
              </Link>
            </li>
          ))}
        </div>

      </main>
    </>
  )
}
