import Header from "@/components/header"
import Head from "next/head"
import loginStyles from '@/styles/Login.module.css'

export default function Login() {
    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Header />
            Login Page
        </>
    )
}