import Header from "@/components/header"
import Head from "next/head"
import profileStyles from '@/styles/Profile.module.css'

export default function Profile() {
    return (
        <>
            <Head>
                <title>Dein Profil</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Header />
            Profile Page              
        </>
    )
}