import Header from "@/components/Header"
import Head from "next/head"
import registerStyles from '@/styles/Register.module.css'

export default function Register() {
    return (
        <>
            <Head>
                <title>Register</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Header />
            Register Page
        </>
    )
}